version: '2'
services:
  database:
    image: mysql:5.6
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - './.mysql-data/db:/var/lib/mysql'
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: nestjs
      MYSQL_USER: root
      MYSQL_PASSWORD: 12345678
